class BannedWordsService {
  static const List<String> bannedWords = [
    // Genel çıplaklık ve cinsel içerik
    'nude', 'naked', 'nudity', 'nakedness',
    'nipple', 'nipples', 'nippled',
    'tits', 'tit', 'titted',
    'breasts', 'breast', 'breasted',
    'boobs', 'boob', 'boobed',
    'ass', 'asses', 'assed',
    'butt', 'butts', 'butted', 'buttock', 'buttocks',
    'vagina', 'vaginal', 'vaginally',
    'penis', 'penile', 'penilely',
    'pussy', 'pussies',
    'dick', 'dicks', 'dicked',
    'cock', 'cocks', 'cocked',
    'fuck', 'fucks', 'fucked', 'fucking', 'fucker', 'fuckers',
    'sex', 'sexual', 'sexually', 'sexuality', 'sexed', 'sexing',
    'erotic', 'erotica', 'erotically',
    'porn', 'porno', 'pornographic', 'pornography',
    'xxx', 'xxxx',
    'fetish', 'fetishes', 'fetishistic',
    'orgasm', 'orgasms', 'orgasmic', 'orgasmed',
    'cum', 'cums', 'cummed', 'cumming',

    // İç çamaşırı ve cinsel çağrışım
    'panties', 'panty', 'pantied',
    'lingerie', 'lingeries',
    'underwear', 'underwears',
    'thong', 'thongs', 'thonged',
    'bralette', 'bralettes',
    'bra', 'bras', 'braed',
    'bikini', 'bikinis', 'bikinied',

    // Diğer yaygın kelimeler
    'suck', 'sucks', 'sucked', 'sucking', 'sucker', 'suckers',
    'anal', 'anally', 'analingus',
    'oral', 'orally', 'oralingus',
    'shemale', 'shemales',
    'blowjob', 'blowjobs', 'blow-job', 'blow-jobs',
    'handjob', 'handjobs', 'hand-job', 'hand-jobs',
    'titfuck', 'titfucks', 'tit-fuck', 'tit-fucks',
    'cunnilingus',
    'masturbation', 'masturbate', 'masturbates', 'masturbated', 'masturbating',
    'hardcore', 'hard-core',
    'hotgirl', 'hot-girl', 'hotgirls', 'hot-girls',
    'hotwoman', 'hot-woman', 'hotwomen', 'hot-women',
    'erotica', 'eroticas',
    "sex",
    "sexual",
    "intercourse",
    "nude",
    "naked",
    "porn",
    "pornography",
    "pornographic",
    "hardcore",
    "softcore",
    "adult",
    "explicit",
    "xxx",
    "nsfw",
    "lewd",
    "erotic",
    "fetish",
    "sensual",
    "seduce",
    "seduction",
    "foreplay",
    "strip",
    "striptease",
    "stripper",
    "make love",
    "lust",
    "horny",
    "aroused",
    "pleasure",
    "orgasm",
    "climax",
    "sexual act",
    "sexual content",
    "sexual activity",
    "sexual scene",
    "intercourse scene",

    // Male anatomy
    "penis",
    "cock",
    "dick",
    "dildo",
    "balls",
    "testicles",
    "shaft",
    "foreskin",
    "cum",
    "ejaculate",
    "sperm",
    "semen",

    // Female anatomy
    "pussy",
    "vagina",
    "clitoris",
    "labia",
    "boobs",
    "tits",
    "nipples",
    "breasts",
    "areola",
    "milk",
    "cumshot",
    "creampie",

    // Sexual acts
    "fuck",
    "fucked",
    "fucking",
    "fucker",
    "blowjob",
    "handjob",
    "footjob",
    "rimjob",
    "jerk off",
    "jacking off",
    "masturbate",
    "masturbation",
    "suck",
    "sucking",
    "lick",
    "licking",
    "oral sex",
    "anal sex",
    "anal",
    "doggystyle",
    "69",
    "deepthroat",
    "threesome",
    "foursome",
    "group sex",
    "bondage",
    "spanking",
    "submission",
    "dominatrix",
    "bdsm",
    "slave",
    "submissive",
    "dominant",
    "discipline",
    "fetish",
    "kink",
    "orgy",
    "cum in",
    "cum on",
    "squirt",
    "moan",
    "groan",
    "sex toy",
    "sex toys",
    "vibrator",
    "buttplug",
    "strapon",
    "pegging",
    "handcuff",
    "whip",

    // Porn/industry words
    "camgirl",
    "cam boy",
    "cam model",
    "escort",
    "escort service",
    "call girl",
    "callboy",
    "prostitute",
    "hooker",
    "sex worker",
    "brothel",
    "onlyfans",
    "fanhouse",

    // Extreme / illegal
    "rape",
    "raping",
    "molest",
    "molestation",
    "child porn",
    "underage",
    "teen sex",
    "incest",
    "bestiality",
    "beast sex",
    "zoophilia",
    "necrophilia",
    "snuff",
    "nonconsensual",

    // Slang / variations
    "f u c k",
    "f.u.c.k",
    "fuk",
    "fck",
    "fuxk",
    "fuq",
    "fking",
    "fked",
    "jerk",
    "jerking",
    "cumshot",
    "cumming",
    "cummed",
    "wank",
    "wanking",
    "p0rn",
    "pr0n",
    "n00d",
    "n00dz",
    "nudes",
    "nudez",
    "boobies",
    "titties",
    "titty",
    "d1ck",
    "c0ck",
    "p3nis",
    "pusy",
    "pussi",
    "asshole",
    "arse",
    "butt",
    "booty",
    "buttocks",
    "cameltoe",
    "panties",
    "lingerie",
    "thong",
    "bikini",
    "seductive",
    "provocative",
    "suggestive",
    "sext",
    "sexting",
    "sex chat",
    "adult chat",
    "naked woman",
    "naked man",
    "undressing",
    "strip dance",
    "lapdance",
    "hentai",

    // Risky emojis / symbolic
    "🍆",
    "🍑",
    "💦",
    "👅",
    "😈",
    "🔥🍑",
    "🍆🍑",
    "🍑💦",
    "🍆💦",
  ];

  /// Checks if the given prompt contains any banned words
  /// Returns a BannedWordsResult with the first found banned word or null if none found
  static BannedWordsResult checkPrompt(String prompt) {
    final lowerPrompt = prompt.toLowerCase();

    for (final bannedWord in bannedWords) {
      if (lowerPrompt.contains(bannedWord.toLowerCase())) {
        return BannedWordsResult(
          hasBannedWord: true,
          bannedWord: bannedWord,
        );
      }
    }

    return BannedWordsResult(hasBannedWord: false);
  }
}

class BannedWordsResult {
  final bool hasBannedWord;
  final String? bannedWord;

  BannedWordsResult({
    required this.hasBannedWord,
    this.bannedWord,
  });
}
