// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBLAnJjnPzo4J67kcEuw0Moj7o3K2p82s',
    appId: '1:729242676224:android:6bf917e7b5b4ef971bfce5',
    messagingSenderId: '729242676224',
    projectId: 'ginowl-ginfit',
    storageBucket: 'ginowl-ginfit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKAilkVBPc7sWs-K_DpCsCgdWHnajuCUQ',
    appId: '1:729242676224:ios:b585ac46adac8d7a1bfce5',
    messagingSenderId: '729242676224',
    projectId: 'ginowl-ginfit',
    storageBucket: 'ginowl-ginfit.firebasestorage.app',
    androidClientId: '729242676224-lm2h5prnk3crrb9e1s4it92oape5tbpq.apps.googleusercontent.com',
    iosClientId: '729242676224-29sr201jv6ep4f6jmgfso8bd66o2kdgf.apps.googleusercontent.com',
    iosBundleId: 'com.comby.ai.outfit.generator.tryon.wardrobe.fitcheck.style',
  );
}
