// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAoV_L83zs2IQGhvuQfs2XvA-LCd4S-o0',
    appId: '1:793286859298:web:e21f0642514dfac85a887b',
    messagingSenderId: '793286859298',
    projectId: 'disciplify-26970',
    authDomain: 'disciplify-26970.firebaseapp.com',
    databaseURL: 'https://disciplify-26970-default-rtdb.firebaseio.com',
    storageBucket: 'disciplify-26970.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3QUYqjoFMKBs6UDB4HdFs7qINiOgwYKg',
    appId: '1:793286859298:android:448dbed13209aa825a887b',
    messagingSenderId: '793286859298',
    projectId: 'disciplify-26970',
    databaseURL: 'https://disciplify-26970-default-rtdb.firebaseio.com',
    storageBucket: 'disciplify-26970.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZnEpSBnRvvhDZsQs0lKHHenaCA8aG5_c',
    appId: '1:793286859298:ios:c0222c7b337ff7315a887b',
    messagingSenderId: '793286859298',
    projectId: 'disciplify-26970',
    databaseURL: 'https://disciplify-26970-default-rtdb.firebaseio.com',
    storageBucket: 'disciplify-26970.firebasestorage.app',
    androidClientId:
        '793286859298-1vkvvdo2bodqne7ne88sknthtc7hu1v9.apps.googleusercontent.com',
    iosClientId:
        '793286859298-csip7ubjigejgsvs464d3j443vaocdq9.apps.googleusercontent.com',
    iosBundleId: 'com.ginfit.ai.outfit.generator.fitcheck',
  );
}
