// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhxY9P6XUkac9bt-1fczD90Oi3iXnaEHY',
    appId: '1:729242676224:web:788b19f52a80f80c1bfce5',
    messagingSenderId: '729242676224',
    projectId: 'ginowl-ginfit',
    authDomain: 'ginowl-ginfit.firebaseapp.com',
    storageBucket: 'ginowl-ginfit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBLAnJjnPzo4J67kcEuw0Moj7o3K2p82s',
    appId: '1:729242676224:android:8eae1c9612180bc11bfce5',
    messagingSenderId: '729242676224',
    projectId: 'ginowl-ginfit',
    storageBucket: 'ginowl-ginfit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKAilkVBPc7sWs-K_DpCsCgdWHnajuCUQ',
    appId: '1:729242676224:ios:fec7a451f4171cfb1bfce5',
    messagingSenderId: '729242676224',
    projectId: 'ginowl-ginfit',
    storageBucket: 'ginowl-ginfit.firebasestorage.app',
    iosBundleId: 'com.ginfit.ai.outfit.generator.fitcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKAilkVBPc7sWs-K_DpCsCgdWHnajuCUQ',
    appId: '1:729242676224:ios:fec7a451f4171cfb1bfce5',
    messagingSenderId: '729242676224',
    projectId: 'ginowl-ginfit',
    storageBucket: 'ginowl-ginfit.firebasestorage.app',
    iosBundleId: 'com.ginfit.ai.outfit.generator.fitcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhxY9P6XUkac9bt-1fczD90Oi3iXnaEHY',
    appId: '1:729242676224:web:f089341cea38110c1bfce5',
    messagingSenderId: '729242676224',
    projectId: 'ginowl-ginfit',
    authDomain: 'ginowl-ginfit.firebaseapp.com',
    storageBucket: 'ginowl-ginfit.firebasestorage.app',
  );
}
